### ISSUE TITLE
Error: Module not found

### ISSUE THREAD

**Issue by hungrysquirrel** [brandai/brandai-storybook#4]
Here's a repo I made that has two commits. The first was to get the basic Storybook set up working. Which it does work and the second commit documents when I tried to integrate with Brand.ai and got the errors I describe below. 
https://github.com/hungrysquirrel/storybook/commits/master

Following instructions here for setting up a React Storybook https://voice.kadira.io/react-storybooks-meets-create-react-app-ac8a3f32cc79

```npm run storybook```
Works great. The intro Storybook button renders fine.

![react_storybook](https://user-images.githubusercontent.com/232397/27352045-384d91be-55b4-11e7-9f5c-03ff9d6d3209.png)

Following instructions here is where things break down
https://github.com/brandai/brandai-storybook#getting-started

```npm install --save-dev brandai-storybook@<1.0.0``` does not work. I believe I am using Storybook 2.35.3. I get the following message in my terminal ```-bash: 1.0.0: No such file or directory```

```
Hello Button
ERROR in ./.storybook/addons.js
Module not found: Error: Cannot resolve module '@storybook/react/addons' in /Users/jmrubins/hello-react/.storybook
 @ ./.storybook/addons.js 3:0-34
ERROR in ./~/brandai-storybook/dist/manager.js
Module not found: Error: Cannot resolve module '@storybook/addons' in /Users/jmrubins/hello-react/node_modules/brandai-storybook/dist
 @ ./~/brandai-storybook/dist/manager.js 11:14-42
```

![react_storybook](https://user-images.githubusercontent.com/232397/27351956-e1151bba-55b3-11e7-8994-d08cfeca5e7f.png)

**Comment by hungrysquirrel** [comment]
I updated my local Storybook to the latest version. I no longer have the errors I posted above but I am not seeing my Brand.ai storybook for button or any other component when I past in the JSON url per your set up instructions.

Here's what I see. The preset storybooks for the basic install from Storybook but nothing from my Brand.ai JSNO feed.

![storybook](https://user-images.githubusercontent.com/232397/27408789-3fd66dea-5693-11e7-9078-3ae7011877d3.png)


In the addon.js file...
Is this a placeholder for the JSON url or is this a variable?
```register({ dataUrl:'<brandai-data-export-url>' });```

The URL I get from the JSON styles output pasted here...Is this the correct location?

![t2-ui-kit_-_hungrysquirrel___brand_ai](https://user-images.githubusercontent.com/232397/27408751-0cb73f8e-5693-11e7-874b-398f8e20d35a.png)

**Comment by kimmajor** [comment]
1) missing module: There were missing apostrophes in the npm command. Readme corrected to
npm install --save-dev brandai-storybook@"<1.0.0"

2) The value of the dataUrl property should be the data-export url you copied from within brand.ai.
For example:
`register({ dataUrl:'https://assets.brand.ai/kim-test-org/dev-1/style-data.json?exportFormat=list&key=xyz' });
`
3) The url you insert into brand.ai should be the url to the story from within storybook. For example, the url to the "with text" story in your repo would be:
http://localhost:9009/?selectedKind=Button&selectedStory=with%20text&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel

**Comment by hungrysquirrel** [comment]
@kimmajor Thank you for fixing the error.

I need a little help understanding how these dots are connected.

I added my Brand.ai JSON url to the data export URL. What purpose does that serve? 

There's a lot that's new for me here. I had an expectation that would give me a list of stories from my Brand.ai set up that correspond to each of my UI elements.

For example in my JSON export from Brand.ai I have a tooltip
```
{
				"name": "Tooltips",
				"components": [
					{
						"url": "https://user-images-secure.brand.ai/hungrysquirrel/t-2-ui-kit/Tooltip-D46B5909-3F31-4F39-9B16-073665F7F53A-rklkDML_mZ.png?Expires=1500734646&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91c2VyLWltYWdlcy1zZWN1cmUuYnJhbmQuYWkvaHVuZ3J5c3F1aXJyZWwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTUwMDczNDY0Nn19fV19&Signature=Q3l0rrEaDoeCKH1D6XPGrwgJ7DI084Lh7YkzNAR-T6CghNa6ic~Iaj8jTYpYoDaM~w3kwpsbHzt4wOirKXxqztgGr4CT1onrKdEwy1oDXg7vPwpvjuqTIQ05QZVrZ6Zu~kJc3nzLKq99xAWBjj8uHhKO8H3rgqR0P1EqTqQwR1tF6o2gkv32hRcf7fm6k0TvPs08q9oaE2hEfzfSWQU0nroenuCoWEWuR0NdpHM357NlVuj6Bc8e7umaWGOtTav~qcdqyJYGWM5NS1De85xIqU0SNpgTPw~J-HCKfTBzHR8vI0YNVAGmi13J3FF5DoOwp6KDEU6iLsh2GZvcZqvY0g__&Key-Pair-Id=APKAJC75MYF5XWMI6QCQ",
						"fileName": "Tooltip.png",
						"displayName": "Tooltip",
						"backgroundColor": null,
						"extension": "png"
					}
				]
			},
```

Do I then need to go to my Storybook install and add a new story in ```src/stories/<tooltip.js> ? Is there some sort of boilerplate way to import my stories from Brand.ai?

I hope my questions make sense. I am very appreciative of any direction you can offer me in learning how to make storybooks for my Brand.ai work I imported from Sketch App.

**Comment by kimmajor** [comment]
Indeed a few moving parts here ;) I'll try to connect the dots.
**The design library:**
You build your UI components and when exported you get a JSON document similar to what you have above. However, if you had pasted a storybook URL in Brand.ai for the component, you would have some extra data, like the following:

```
"name": "Buttons",
"components": [{
        "url": "https://public-images.brand.ai/preview/Standard%20-%20Default-AC50AFD4-3BDE-4D6F-84BC-4B8C408-rybBiBKsWx.png",
        "fileName": "Standard - Default.png",
        "displayName": "Standard - Default",
        "extension": "png",
        "storybook": {
            "kind": "Button",
            "storyName": "default view",
            "url": "http://localhost:9010/?selectedKind=Button&selectedStory=default%20view&full=0&down=1&left=1&panelRight=0&downPanel=brandai%2Fassets-viewer%2Fassets-panel"
        }
    }]

```

Storybook:
When you start storybook, we fetch the design library using the url you set in the register method. When you select a story in in storybook, storybook notifies the addon with the "kind" and "name" of the story. 
We do a lookup to check if the current "kind" and "name" of the story is present in the JSON returned when fetching the library. If there's a match, we render the component image, name, description...

Hope this clarifies.

**Comment by hungrysquirrel** [comment]
@kimmajor 

I think I am starting to understand.

So steps are as follows?
1. Make a component in Sketch and update Brand.ai to have that component in the library
1. Add a new story in my react app here src/stories/tooltip.js ? What do I need in that file? What is the format? Or is it not necessary and I am overlooking a key concept? I have two default files made by the vanilla Storybook install https://github.com/hungrysquirrel/storybook/tree/master/src/stories
1. Based on your feedback to question #2 Do I paste in the URL from that localhost story into the Brand.ai React Storybook field in Brand.ai?
1. How do I get my storybook to have all of these fields and the actual live tooltip? Like the example below?

<img width="932" alt="brandai_brandai-storybook__the_brand_ai_viewer_displays_ui_components_from_a_brand_ai_design_library_in_react_storybook" src="https://user-images.githubusercontent.com/232397/27455410-06f3ebfa-5752-11e7-8ef8-8b637a6a91fd.png">

**Comment by kimmajor** [comment]
1) yes
2) just create a new story. Once you paste the url of the story into the brand.ai component the plugin will do the matching. No need to add anything special in the story.
3) yes. We'll add a brand.ai setting for overriding the host so that the connection won't be broken when/if you publish your storybook
4) That's just an in-house storybook decorator we're using. You can find similar functionality in the following addons for storybook
https://github.com/storybooks/storybook/tree/master/addons/info
https://www.npmjs.com/package/storybook-addon-props

**Comment by hungrysquirrel** [comment]
When I create a new story is that as simple as making an new file called <StoryName.js> in my stories directory? Should it be added to the navigation automatically or do I need to update my ```index.js``` file with a link to the new story?

For example I made a new story file called Chip.js but I did not see it show in the Storybook nav. If I have to add it manually how do I know the full URL. 

Could you share some of the in-house set up including the decorators and URL construction pasted into Brand.ai? I am having a hard time following the set up. I would really appreciate seeing some sample files since I am having so many bugs.

My latest bug:
If I make the new empty story file for Chip.js and paste in the URL into Brand.ai (similar structure as the URL for my button). The chip art now appears in the Tooltip story in the web UI and I double checked to make sure the storybook URL in Brand.ai is not the same.

I really want to get this workflow. As a way to return the generosity of your help I'd be happy to document the workflow once I get it working and post an article on Medium or something.

**Comment by kimmajor** [comment]
This doesn't seem directly related to the addon so I'll close this issue. Let's continue on a private thread (kim@brand.ai)
