### ISSUE TITLE
Anchor link to UI element from Storybook to Brand.ai UI component list

### ISSUE THREAD

**Issue by hungrysquirrel** [brandai/brandai-storybook#6]
**Feature request**
As a consumer of a Brand.ai Story within Storybook I see an example component and it's supportive image asset in the Design Library. In the Design Library tab I see a link back to the Brand.ai UI kit. I would expect to be able to click the asset or the link and be taken to the Brand.ai hosted UI library and anchor linked to the corresponding component.

**Comment by kimmajor** [comment]
Agree! I'll post here when it's available

**Comment by kimmajor** [comment]
published v1.0.2
